version: '3'
services:
  wallabag:
    image: wallabag/wallabag
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SYMFONY__ENV__DATABASE_DRIVER: pdo_mysql
      SYMFONY__ENV__DATABASE_HOST: ${MYSQL_HOST}
      SYMFONY__ENV__DATABASE_PORT: 3306
      SYMFONY__ENV__DATABASE_NAME: ${MYSQL_DATABASE}
      SYMFONY__ENV__DATABASE_USER: ${MYSQL_USER}
      SYMFONY__ENV__DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      SYMFONY__ENV__DATABASE_CHARSET: utf8mb4
      SYMFONY__ENV__MAILER_HOST: ${MAILER_HOST}
      SYMFONY__ENV__MAILER_USER: ${MAILER_USER}
      SYMFONY__ENV__MAILER_PASSWORD: ${MAILER_PASSWORD}
      SYMFONY__ENV__FROM_EMAIL: ${FROM_EMAIL}
      SYMFONY__ENV__DOMAIN_NAME: ${SERVER_URL}
      SYMFONY__ENV__SERVER_NAME: ${SERVER_NAME}
    ports:
      - "${SERVER_PORT}:80"
    volumes:
      - ${WALLABAG_DATA_IMAGES}:/var/www/wallabag/web/assets/images
      - ${WALLABAG_DATA_CONFIG}:/var/www/wallabag/app/config:rw

  db:
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ${MYSQL_DATA}:/var/lib/mysql

  redis:
    image: redis:alpine
    restart: unless-stopped
